### ISSUE TITLE
Solver not working at all since update

### ISSUE THREAD

**Issue by elreymu** [theonlydude/RandomMetroidSolver#4] opened 2018-02-08 22:53 UTC
Would like to report that now every rom i upload to the solver won't work anymore.
After uploading them , it will always say it's not finishable. (Tried all combinations of difficulties and other settings and getting the same results) the spoiler will be completely blank each time.
all of the roms i am using are from the online randomizer.

**Comment by theonlydude** [comment] 2018-02-08 22:55
Yes, we're aware of the issue and working on a fix.

**Comment by theonlydude** [comment] 2018-02-08 23:00
It's fixed.

**Comment by elreymu** [comment] 2018-02-08 23:03
Oh alright, reported it just in case this went unnoticed for longer.
also taking the chance to suggest to add a wiki hyperlink to each location name in the spoiler section for the people who are not very familiar with item locations (Just like it's already done in the techniques section)

**Comment by flohgh** [comment] 2018-02-08 23:15
You did the right thing, no worries! :)

Please tell us if you experience anymore problems.

Regarding your suggestion, we'll take a look at it, please create a separate issue for it as we will close this one when we're sure the website problem is over.

**Comment by theonlydude** [comment] 2018-02-15 11:33
the issue is fixed.

**Closed by theonlydude** 2018-02-15 11:33 UTC
