### ISSUE TITLE
Possible Casual logic bug?

### ISSUE THREAD

**Issue by lenophis** [theonlydude/RandomMetroidSolver#29] opened 2019-06-05 07:31 UTC
Mistress Saeko was playing seed 6773509 with full randomization, casual skills preset, default settings preset, full randomization, and medium progression speed.

Space Jump is locked at Croc Escape, which requires Hi-Jump+Speed or Grapple. However...
![Welp](https://user-images.githubusercontent.com/29736776/58937993-8d98d580-8739-11e9-98a3-7d59ee504fe6.png)
![Welp 2](https://user-images.githubusercontent.com/29736776/58937998-91c4f300-8739-11e9-9fa1-da45f7119d69.png)
![Welp 3](https://user-images.githubusercontent.com/29736776/58938002-94bfe380-8739-11e9-9d37-f9a1afc61ca0.png)
![Welp 4](https://user-images.githubusercontent.com/29736776/58938005-97bad400-8739-11e9-86b6-6bca4583b45b.png)
![Welp 5](https://user-images.githubusercontent.com/29736776/58938014-9b4e5b00-8739-11e9-92cc-452938d82fe5.png)

As you can see from the screenshots, the Wrecked Ship was absolutely stacked. The potential problem is that CWJ across the moat was absolutely required, but should that not be the case with these settings?

The only key items acquired before CWJ were Morph Ball, Varia Suit, Charge Beam, and Ice Beam.

As a sidenote, the Justin Bailey graphical patch, as well as Kejardon's Total Control patches were applied. They should not have affected anything regarding item placement.

**Comment by theonlydude** [comment] 2019-06-05 10:41
Hello,
When in doubt about the logic you can use the solver and its spoiler path.
In the spoiler it does pick up space jump before going to wrecked ship.

**Comment by flohgh** [comment] 2019-06-05 12:52
not a bug, closing

**Closed by flohgh** 2019-06-05 12:52 UTC
Labels: question

**Comment by lenophis** [comment] 2019-06-05 17:55
Then perhaps you guys can explain where the Morph Ball Bombs were. I investigated this seed after getting assured, backed up by screenshot, that she had explored everywhere she could with two exceptions.

![VARIA_Randomizer_FX6773509_casual_medium000](https://user-images.githubusercontent.com/29736776/58977829-1d696e80-8790-11e9-906d-386d493fe44d.png)
![VARIA_Randomizer_FX6773509_casual_medium001](https://user-images.githubusercontent.com/29736776/58977833-1f333200-8790-11e9-8fa4-f0c353663026.png)
![VARIA_Randomizer_FX6773509_casual_medium002](https://user-images.githubusercontent.com/29736776/58977836-20fcf580-8790-11e9-9bcb-e7f9e1b659d6.png)
![VARIA_Randomizer_FX6773509_casual_medium003](https://user-images.githubusercontent.com/29736776/58977839-22c6b900-8790-11e9-9f17-aa9963a02540.png)

The Ice Beam check isn't present because she reset after finding out it was a Reserve Tank. Wallflower/Crumble Tower was ammo.

She could not get to the front end of Gauntlet, which I checked and confirmed it was a super missile.
![super](https://user-images.githubusercontent.com/29736776/58977928-5dc8ec80-8790-11e9-8fba-0d8861775e68.png)

She also could not get to Croc's PB, which was again, a super missile.
![super again](https://user-images.githubusercontent.com/29736776/58977954-6e796280-8790-11e9-8832-705a65a1dbd3.png)

I asked her about doing GGG to get to Grapple, she said she could do it but I just went ahead and did it, which was garbage.

That leaves Waterway, X-Ray scope, and the Grapple Missile as the last possible locations to check, none of which are attainable.

Also, are you saying that doing an X-adjusted IBJ to get to Space Jump is in *casual* logic? You have to do a mid-air repositioning to get that particular item. Much easier with Hi-Jump, but you can clearly see that Hi-Jump is locked away in the Wrecked Ship. *THAT* is in casual logic? Are you kidding me?

**Comment by flohgh** [comment] 2019-06-05 20:39
Xray with ice beam and a ton of etanks is in logic, so it's probably there.

Repeating what theonlydude said: check the seed in the solver, all the answers will be there.

The I in IBJ does mean infinite. The bomb jump to the left is tricky indeed, that's why it won't be required when hell running

**Comment by lenophis** [comment] 2019-06-05 21:05
"Xray with ice beam and a ton of etanks is in logic, so it's probably there."

You are saying forcefully taking damage is *in logic* for a "Casual" logic setting? This is not Super Metroid: Redesign.

Also, I would like to point out "so it's probably there."

I thought the same thing about the progression possibly being in the front end of the gauntlet. Wasn't there. Wasn't at Croc PB's either. I actually grabbed the seed and checked these locations. I took the time to CWJ the moat and investigate Wrecked Ship to see what was going on.

You make it sound like you didn't check at all. You don't even know if Bombs (or anything other than more ammo) are at the X-Ray in this seed. You're telling me "use the solver" when I already put more effort into this seed and its logic than you did in reading this!

"Repeating what theonlydude said: check the seed in the solver, all the answers will be there."

I attempted to regenerate the seed with the number last night to see what was up with this seed, and could not. I find the site difficult to navigate and not really user-friendly in some aspects.

"The I in IBJ does mean infinite."

See, now I'm just going to be a smartass.

https://youtu.be/moEy-Pfndcw

There's my video about teaching players how to IBJ, along with any other number of basic techniques.

I've been speedrunning this for 9 years, and have been playing SM itself since 1995. NEStroid since 1988. I know what IBJ is.

What I'm saying is, since you're just dismissing anything being brought up, is that this is a CASUAL seed. This heavily implies NOT doing "speedrunning techniques." Damage boosting is definitely not a casual thing to do. Forcefully taking damage is not a casual thing to do.

That's why I brought all of this up in the first place. Something is definitely out of place. There's a reason why, at least in the Crossover, "Casual" implies only simple wall jumping, simple IBJ (only vertical), and shinesparking (vertical, horizontal, or diagonal). No other techniques are used. Only the stuff the game teaches you.

What does "Casual" imply here?

**Comment by flohgh** [comment] 2019-06-05 21:12
It sounds like I didn't check because I was commuting and I didn't. 

The logic in VARIA is transparent, so you don't have to read between the lines or check the source code to see what "casual" means. Just go to the preset page and load the casual preset.

**Comment by flohgh** [comment] 2019-06-05 21:18
I do agree that standard presets deserve a better explanation, and we should add that.

The spirit behind the "casual" one is "nothing too hard to learn and nothing that requires going fast". So no hellruns, no suitless Maridia, and basic tricks/glitches that don't require to learn a difficult setup.

**Comment by flohgh** [comment] 2019-06-05 21:27
Also, if some tricks of for instance the casual presets are considered too difficult, you can either:
- use another preset, such as noob or smrat (this one was made by Jaychalke to mimic the crossover normal logic)
- create a custom preset with what you know
- create a seed with the casual preset but lowering the seed max difficulty. For instance, if you choose casual preset+medium diff, IBJ or GGG won't be required because they're labelled "hard".

**Comment by theonlydude** [comment] 2019-06-05 21:59
when you're not sure about the logic there's the interactive tracker, it's the tool I would have die for when I start playing randomized seeds.

**Comment by flohgh** [comment] 2019-06-05 23:30
I generated the seed using the number you provided with casual logic and default rando settings, and ran it into the solver. Bomb was indeed at XRay, accessible with Ice beam and the 11 available health tanks.
